rbac: false

controller:
  secret:
    enabled: true
    data:
      userinitcfg.yaml: 
        always_reload: true
        users:
        -
          Fullname: admin
          Password: 
          Role: admin

manager:
  svc:
    type: NodePort

resources:
  limits:
    cpu: 400m
    memory: 2792Mi
  requests:
    cpu: 100m
    memory: 2280Mi

k3s:
  enabled: true
